### ISSUE TITLE
Clustering for the Individual Donor

### ISSUE THREAD

**Issue by snacks** [Greenstand/treetracker-map-api-DEPRECATED#10]
Please see below conversation. 

	
Gwen 7 minutes ago
I'd like for the user to be able to zoom out and still see where 'their' trees are in relation to other trees.
zaven 6 minutes ago
yeah that's what i was thinking
Gwen 6 minutes ago
so like, that particular cluster could have a star in the pin instead of the number? or be a different color etc
zaven 6 minutes ago
there's a few options..
zaven 4 minutes ago
there's keeping the polygon on the map
zaven 4 minutes ago
there's changing the color of the cluster
zaven 4 minutes ago
there's just keeping an extra pin on top of the actual cluster pins
zaven 4 minutes ago
it's also complex because the use cases are different if a donor has funded 5 trees vs 40,000 trees
zaven 3 minutes ago
40,000 trees will surely be mixed into multiple clusters
zaven 3 minutes ago
ok
zaven 3 minutes ago
i think that it should be possible to modify the query such that
zaven 3 minutes ago
trees for a given donor are clustered separately from all other trees
zaven 2 minutes ago
so you would get a set of clusters that include clusters for that one donor, and clusters for all other trees
zaven 2 minutes ago
this would be done by modifying a group by clause or something, or simply executing 2 queries and merging the result

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-web-map/issues/55
