### ISSUE TITLE
Don't reload tree pins

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-map-api-DEPRECATED#13]
Once the map is zoomed in enough to view the tree pins, they should not be be removed and added to the map by panning or zooming (until the map is zoomed out enough to switch back to clusters).   The current behavior is a major slow down.  This is a bit tricky because panning could cause new trees to be added to the map.  I suggest some bookkeeping to keep track of what tree points are on the map, and to not remove/re-add them.

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-web-map/issues/27
