### ISSUE TITLE
Clustering and Data

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-map-api-DEPRECATED#8]
e want to return a convex null and a link of the first 50 image urls for each cluster. See links below for ideas of an approach. This will be incorporated into the trees/ endpoint.

https://gis.stackexchange.com/questions/199671/how-to-include-aggregate-field-values-of-clustered-points
https://postgis.net/docs/ST_ConvexHull.html

**Comment by deepwinter** [comment]
Current clustering SQL

let sql = "SELECT 'cluster' AS type, ST_AsGeoJSON(ST_Centroid(clustered_locations)) centroid, ST_AsGeoJSON(ST_MinimumBoundingCircle(clustered_locations)) circle, ST_NumGeometries(clustered_locations) count FROM ( SELECT unnest(ST_ClusterWithin(estimated_geometric_location, $1)) clustered_locations from trees ) clusters";

**Comment by deepwinter** [comment]
Got it!

```
WITH clusters AS(
    SELECT unnest(ST_ClusterWithin(estimated_geometric_location, .1)) AS collection
       FROM trees)
, unpacked AS( --unpacking GeomCollections
    SELECT row_number() OVER () AS cluster_id, (ST_DUMP(collection)).geom AS estimated_geometric_location 
       FROM clusters)
, unclustered AS (
  SELECT cluster_id, 
                estimated_geometric_location,
                rank() OVER(PARTITION BY cluster_id ORDER BY estimated_geometric_location) as rank
         FROM unpacked
)
SELECT cluster_id as gid,
    string_agg(case when rank < 50 then trees.image_url end  , ';' ) AS image_urls,
    ST_Centroid(ST_Collect(estimated_geometric_location)) AS estimated_geometric_location, 
    COUNT(1) AS numgeom
    FROM trees
    INNER JOIN unclustered USING(estimated_geometric_location)
    GROUP BY cluster_id;
```

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-web-map/issues/27
